import Head from 'next/head';
import { GetStaticProps } from 'next';
import ProductList from '@/components/organisms/ProductList';

export default function Home({ data }: any) {
	const {
		data: { results: comics },
	} = data;

	return (
		<>
			<Head>
				<title>Desafio Marvel NeoApp</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<>
				<ProductList products={comics} />
			</>
		</>
	);
}

export const getStaticProps: GetStaticProps = async () => {
	const res = await fetch(
		`http://gateway.marvel.com/v1/public/comics?format=comic&limit=10&offset=10&ts=1&apikey=${process.env.NEXT_PUBLIC_API_KEY}&hash=f3c107943b00a0293c39eb2c158a731a`
	);

	const data = await res.json();

	return {
		props: {
			data,
		},
		revalidate: 10,
	};
};
